name: Android CI

on:
  push:
    branches: [ main, master, develop, "release/**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required Android SDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build (assemble all variants)
        run: ./gradlew --no-daemon assemble

      - name: Publish build outputs
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-outputs
          path: |
            app/build/outputs/**/*.apk
            app/build/outputs/**/*.aab
            app/build/outputs/**/*.aar
            **/build/reports/**
